;; Generates the Gregorio vs. lilygabc side-by-side comparison

(use-modules
 (ice-9 rdelim)
 (ice-9 textual-ports))

(define header "\\documentclass[a4paper, 12pt]{article}

\\usepackage{lyluatex}
\\usepackage{gregoriotex}

\\title{lilygabc visual tests: comparison with gregorio}

\\begin{document}
\\maketitle")

(define placeholder "<snippet>")

(define item-template '("% " " ----------
\\noindent
\\begin{minipage}[t]{0.3\\textwidth}
  \\texttt{" "}
\\end{minipage}
\\begin{minipage}[t]{0.3\\textwidth}
  \\gabcsnippet{" "}
\\end{minipage}
\\begin{minipage}[t]{0.3\\textwidth}
  \\begin{lilypond}
    \\include \"../../lilygabc.ily\"
    \\score {
      \\gabc \"" "\"
      \\layout { \\lilygabcModernGregorianStemlessLayout }
    }
  \\end{lilypond}
\\end{minipage}"))

(define footer "\\end{document}")

(define (make-title str)
  (string-append "\\section*{" str "}\n"))

(define (make-item str)
  (string-join item-template str))



(display "% Generated by generate.scm")
(newline)
(display header)
(newline)
(call-with-input-file
    "snippets.txt"
  (lambda (file)
    (do ((line (read-line file) (read-line file))) ((eof-object? line))
      (cond
       ((string-prefix? "#" line)) ; do nothing
       ((= 0 (string-length (string-trim-both line)))) ; do nothing
       ((string-prefix? "=" line)
        (display (make-title (string-trim-both (substring line 1))))
        (newline))
       (else
        (display (make-item line))
        (newline) (newline))))))
(display footer)
(newline)
